export const PRODUCTS_ACTION = {
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_PENDING: 'GET_PRODUCTS_PENDING',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
    SET_PRODUCTS_COUNT: 'SET_PRODUCTS_COUNT',
    CREATE_PRODUCTS_SUCCESS: 'CREATE_PRODUCTS_SUCCESS',
    CREATE_PRODUCTS_PENDING: 'CREATE_PRODUCTS_PENDING',
    CREATE_PRODUCTS_ERROR: 'CREATE_PRODUCTS_ERROR',
    DELETE_PRODUCTS_SUCCESS: 'DELETE_PRODUCTS_SUCCESS',
    DELETE_PRODUCTS_PENDING: 'DELETE_PRODUCTS_PENDING',
    DELETE_PRODUCTS_ERROR: 'DELETE_PRODUCTS_ERROR',
    EDIT_PRODUCTS_SUCCESS: 'EDIT_PRODUCTS_SUCCESS',
    EDIT_PRODUCTS_PENDING: 'EDIT_PRODUCTS_PENDING',
    EDIT_PRODUCTS_ERROR: 'EDIT_PRODUCTS_ERROR',
    LIKE_PRODUCTS_SUCCESS: 'LIKE_PRODUCTS_SUCCESS'
}

export const defaultGetProductsParams = {
    _limit: 8,
    _page: 1,
}