export const API_URL = 'http://localhost:8000'

export const API = {
    PRODUCTS: 'products',
    USER: 'users'
}

export const PRODUCTS_ACTION = {
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_PENDING: 'GET_PRODUCTS_PENDING',
    GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
    SET_PRODUCTS_COUNT: 'SET_PRODUCTS_COUNT',
    CREATE_PRODUCTS_SUCCESS: 'CREATE_PRODUCTS_SUCCESS',
    CREATE_PRODUCTS_PENDING: 'CREATE_PRODUCTS_PENDING',
    CREATE_PRODUCTS_ERROR: 'CREATE_PRODUCTS_ERROR',
}

export const USER_ACTION = {
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_PENDING: 'GET_USER_PENDING',
    GET_USER_ERROR: 'GET_USER_ERROR'
}

export const AUTH_METHOD = {
    REGISTER: 'register',
    LOGIN: 'login',
}


export const defaultGetProductsParams = {
    _limit: 8,
    _page: 1,
}